export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const VALIDATE_REQUEST = "VALIDATE_REQUEST"
export const VALIDATE_SUCCESS = "VALIDATE_SUCCESS"
export const VALIDATE_FAILURE = "VALIDATE_FAILURE"

export const ACTIVE_REQUEST = "ACTIVE_REQUEST"
export const ACTIVE_SUCCESS = "ACTIVE_SUCCESS"
export const ACTIVE_FAILURE = "ACTIVE_FAILURE"

export const COUNTRY_REQUEST = "COUNTRY_REQUEST"
export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS"
export const COUNTRY_FAILURE = "COUNTRY_FAILURE"

export const CURRENCY_REQUEST = "CURRENCY_REQUEST"
export const CURRENCY_SUCCESS = "CURRENCY_SUCCESS"
export const CURRENCY_FAILURE = "CURRENCY_FAILURE"

export const CITY_REQUEST = "CITY_REQUEST"
export const CITY_SUCCESS = "CITY_SUCCESS"
export const CITY_FAILURE = "CITY_FAILURE"

export const CREATE_REQUEST = "CREATE_REQUEST"
export const CREATE_SUCCESS = "CREATE_SUCCESS"
export const CREATE_FAILURE = "CREATE_FAILURE"