export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const API_REQUEST = "API_REQUEST"
export const API_SUCCESS = "API_SUCCESS"
export const API_FAILURE = "API_FAILURE"

export const TABLE_REQUEST = "TABLE_REQUEST"
export const TABLE_SUCCESS = "TABLE_SUCCESS"
export const TABLE_FAILURE = "TABLE_FAILURE"

export const COUNTRY_REQUEST = "COUNTRY_REQUEST"
export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS"
export const COUNTRY_FAILURE = "COUNTRY_FAILURE"

export const CURRENCIE_REQUEST = "CURRENCIE_REQUEST"
export const CURRENCIE_SUCCESS = "CURRENCIE_SUCCESS"
export const CURRENCIE_FAILURE = "CURRENCIE_FAILURE"

export const CITY_REQUEST = "CITY_REQUEST"
export const CITY_SUCCESS = "CITY_SUCCESS"
export const CITY_FAILURE = "CITY_FAILURE"

export const CREATE_REQUEST = "CREATE_REQUEST"
export const CREATE_SUCCESS = "CREATE_SUCCESS"
export const CREATE_FAILURE = "CREATE_FAILURE"

export const GET_ID_REQUEST = "GET_ID_REQUEST"
export const GET_ID_SUCCESS = "GET_ID_SUCCESS"
export const GET_ID_FAILURE = "GET_ID_FAILURE"

export const HASTINUPDATE_REQUEST ="HASTINUPDATE_REQUEST" 
export const HASTINUPDATE_SUCCESS ="HASTINUPDATE_SUCCESS"
export const HASTINUPDATE_FAILURE ="HASTINUPDATE_FAILURE"

